Add new "MarkAs" methods and unit tests for it.
microsoft/Omex pull request #274
Opened 2020-11-02 20:24 UTC by MatusTomko

2020-11-03 10:46 UTC, artempushkin requested changes

2020-11-03 10:46 UTC, artempushkin commented on src/Extensions/Abstractions/Activities/ActivityExtensions.cs
> +		/// MarkAsSuccess
Please make more human readable, I suggest: Set activity result to Success. Similar for the other 2 methods.

2020-11-03 10:46 UTC, artempushkin commented on tests/Extensions/Abstractions.UnitTests/Activities/ActivityExtensionsTests.cs
> +		public void MarkAsSuccess_SetSuccess()
Please change to Set**s**ResultToSuccess. Similar for the other 2 tests.

2020-11-04 15:05 UTC, artempushkin approved these changes
Looks great!

2020-11-04 15:33 UTC, AndreyTretyak approved these changes

2020-11-04 15:34 UTC, merged

2020-11-04 15:34 UTC, AndreyTretyak commented
@MatusTomko  Thank you for your contribution!